### ISSUE TITLE
List of classes should be sorted

### ISSUE THREAD

**Issue by asgeirn** [FINTprosjektet/fint-informasjonsmodell-documentation#2]
Under each package, the list of classes should be sorted.

Alternatives:

1. First by type (main class, abstract class, complex datatype), then by name
1. Only by name

**Comment by fsjovatsen** [comment]
@asgeirn 

![image](https://user-images.githubusercontent.com/6375784/39455712-446281b4-4ce2-11e8-9aab-ab3b13c72d88.png)

Is this ok?

**Comment by asgeirn** [comment]
Excellent! 👍
