### ISSUE TITLE
Pakker med mellomrom må settes sammen i stedet for understrek

### ISSUE THREAD

**Issue by oleanders** [FINTprosjektet/fint-informasjonsmodell-documentation#3]
I Enterprise Architect finnes det en pakke som heter `Vigo Kodeverk`. I dokumentasjonsportalen får den navnet `vigo_kodeverk`:
![image](https://user-images.githubusercontent.com/26850/31327055-c6b49bae-accc-11e7-8e13-c5485bb9dfc8.png)

I Java-modellen gjøres det om til `vigokodeverk`. Slik må det også bli i dokumentasjonsportalen. Se https://github.com/FINTprosjektet/fint-informasjonsmodell/issues/40#issuecomment-335074921

**Comment by OysteinAmundsen** [comment]
Det burde gjøre susen.

**Comment by oleanders** [comment]
@OysteinAmundsen Takk! Jeg kjørte deployment nå. Kan bekrefte at det er løst.
